export const experiences = [
  // === WORK ===
  {
    id: "frontend-zenith",
    title: "Frontend Engineer",
    company: "Zenith Solutions",
    location: "Barcelona, Spain",
    startDate: "March 2024",
    endDate: "Present",
    description: "Developing high-performance web applications for fintech clients.",
    achievements: [
      "Implemented a design system that reduced UI bugs by 40%",
      "Optimized React components, decreasing initial load time by 55%",
      "Led the migration to Vite.js for improved developer experience",
      "Collaborated with backend team to design GraphQL API integrations",
    ],
    type: "work",
  },
  {
    id: "backend-novus",
    title: "Backend Developer",
    company: "Novus Tech",
    location: "Madrid, Spain",
    startDate: "August 2023",
    endDate: "February 2024",
    description: "Built and maintained microservices architecture for e-commerce platforms.",
    achievements: [
      "Designed scalable APIs handling 10k+ requests per minute",
      "Improved system resilience by implementing circuit breaker patterns",
      "Reduced deployment time by 70% through CI/CD pipeline automation",
      "Implemented database sharding to handle growing traffic",
    ],
    type: "work",
  },
  {
    id: "fullstack-orion",
    title: "Full Stack Developer",
    company: "Orion Labs",
    location: "Remote",
    startDate: "January 2023",
    endDate: "July 2023",
    description: "Delivered end-to-end features for SaaS data analytics tools.",
    achievements: [
      "Integrated third-party APIs for data visualization and reporting",
      "Built a real-time notification system using WebSockets",
      "Created reusable UI components in React for faster development",
      "Wrote automated tests achieving 90% coverage",
    ],
    type: "work",
  },
  {
    id: "mobile-aura",
    title: "Mobile App Developer",
    company: "Aura Health",
    location: "Valencia, Spain",
    startDate: "June 2022",
    endDate: "December 2022",
    description: "Developed cross-platform mobile apps for health tracking.",
    achievements: [
      "Implemented offline-first features for remote users",
      "Reduced app crash rate by 25% with proactive monitoring",
      "Integrated Bluetooth device syncing for fitness wearables",
      "Collaborated with UX team to redesign app onboarding flow",
    ],
    type: "work",
  },
  {
    id: "qa-cypher",
    title: "QA Automation Engineer",
    company: "CypherSoft",
    location: "Seville, Spain",
    startDate: "January 2022",
    endDate: "May 2022",
    description: "Automated regression testing for enterprise software solutions.",
    achievements: [
      "Developed Cypress test suites reducing manual testing by 80%",
      "Implemented visual regression testing pipeline",
      "Reduced production bugs by 35% through proactive QA",
      "Collaborated with devs to integrate testing into CI/CD workflow",
    ],
    type: "work",
  },

  // === LEADERSHIP ===
  {
    id: "lead-devconf",
    title: "Lead Organizer",
    company: "DevConf Europe",
    location: "Berlin, Germany",
    startDate: "February 2024",
    endDate: "Present",
    description: "Led the planning and execution of Europe's largest developer conference.",
    achievements: [
      "Coordinated 50+ volunteers for event operations",
      "Increased attendee satisfaction rate to 98%",
      "Negotiated sponsorships totaling €200k",
      "Implemented a hybrid conference format with live streaming",
    ],
    type: "leadership",
  },
  {
    id: "tech-lead-alphacorp",
    title: "Technical Lead",
    company: "AlphaCorp",
    location: "Madrid, Spain",
    startDate: "August 2023",
    endDate: "January 2024",
    description: "Managed a team of 6 developers building enterprise CRM systems.",
    achievements: [
      "Introduced agile ceremonies improving delivery predictability",
      "Mentored junior devs, leading to 3 internal promotions",
      "Oversaw code quality through peer review processes",
      "Coordinated cross-team feature rollouts without downtime",
    ],
    type: "leadership",
  },
  {
    id: "club-president",
    title: "President",
    company: "Barcelona Tech Club",
    location: "Barcelona, Spain",
    startDate: "January 2023",
    endDate: "December 2023",
    description: "Directed community events and hackathons for local developers.",
    achievements: [
      "Grew membership from 200 to 500 members in one year",
      "Organized monthly meetups with average attendance of 80",
      "Partnered with local startups for sponsorships",
      "Launched mentorship program connecting juniors with industry pros",
    ],
    type: "leadership",
  },
  {
    id: "scrum-master-neoapps",
    title: "Scrum Master",
    company: "NeoApps",
    location: "Remote",
    startDate: "July 2022",
    endDate: "December 2022",
    description: "Facilitated agile development for mobile application projects.",
    achievements: [
      "Reduced sprint spillover tasks by 40%",
      "Improved team communication with daily check-ins",
      "Standardized backlog grooming process",
      "Promoted knowledge sharing with internal workshops",
    ],
    type: "leadership",
  },
  {
    id: "hackathon-captain",
    title: "Hackathon Captain",
    company: "TechFest Global",
    location: "Lisbon, Portugal",
    startDate: "April 2022",
    endDate: "June 2022",
    description: "Led a winning team in an international hackathon.",
    achievements: [
      "Designed and pitched a blockchain-based voting platform",
      "Secured first place among 60+ teams",
      "Managed time and resources effectively under pressure",
      "Coordinated team roles to ensure balanced workload",
    ],
    type: "leadership",
  },

  // === EDUCATION ===
  {
    id: "msc-ai",
    title: "MSc in Artificial Intelligence",
    company: "University of Edinburgh",
    location: "Edinburgh, UK",
    startDate: "September 2023",
    endDate: "Present",
    description: "Specializing in machine learning, deep learning, and NLP.",
    achievements: [
      "Achieved distinction in Advanced ML course",
      "Built an AI model for automated essay scoring",
      "Collaborated in a cross-university AI ethics project",
      "Published paper on bias mitigation in ML models",
    ],
    type: "education",
  },
  {
    id: "bsc-compsci",
    title: "BSc in Computer Science",
    company: "Complutense University of Madrid",
    location: "Madrid, Spain",
    startDate: "September 2019",
    endDate: "July 2023",
    description: "Focused on software engineering and data science.",
    achievements: [
      "Graduated top 5% of class",
      "Built capstone project on smart traffic management",
      "Completed internships in backend and frontend development",
      "Led student developer society for 1 year",
    ],
    type: "education",
  },
  {
    id: "exchange-berlin",
    title: "Exchange Program - Computer Science",
    company: "Technical University of Berlin",
    location: "Berlin, Germany",
    startDate: "January 2022",
    endDate: "July 2022",
    description: "Studied human-computer interaction and UX design.",
    achievements: [
      "Completed a UX case study on public transport apps",
      "Collaborated with international students on design sprints",
      "Presented research to Berlin's transport authority",
      "Achieved highest score in HCI course",
    ],
    type: "education",
  },
  {
    id: "online-ml-cert",
    title: "Machine Learning Specialization",
    company: "Coursera / Stanford University",
    location: "Online",
    startDate: "June 2021",
    endDate: "November 2021",
    description: "Online specialization covering supervised and unsupervised learning.",
    achievements: [
      "Built ML pipelines using Scikit-learn and TensorFlow",
      "Completed real-world projects with provided datasets",
      "Implemented algorithms from scratch for learning purposes",
      "Received certification with distinction",
    ],
    type: "education",
  },
  {
    id: "bootcamp-webdev",
    title: "Full Stack Web Development Bootcamp",
    company: "Ironhack",
    location: "Barcelona, Spain",
    startDate: "January 2021",
    endDate: "April 2021",
    description: "Intensive training program covering modern web technologies.",
    achievements: [
      "Built a final project deployed on AWS",
      "Collaborated in teams of 4 using Agile methodology",
      "Learned MERN stack in 12 weeks",
      "Won 'Best Project' award for innovative use of APIs",
    ],
    type: "education",
  },
];
